# This is a basic workflow to help you get started with Actions

name: Compile Examples

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - "examples/**"
      - "src/**"
  pull_request:
    branches: [ master ]
    paths:
      - "examples/**"
      - "src/**"

  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile-examples:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      
      matrix:
        board: [
          {"fqbn": "arduino:avr:uno", "type": "Arduino Uno"},
          {"fqbn": "arduino:megaavr:nona4809", "type": "NanoEvery"},
          {"fqbn": "megaTinyCore:megaavr:atxy7:chip=3217", "type": "Attiny3217"},
          {"fqbn": "adafruit:samd:adafruit_itsybitsy_m0", "type": "ItsyBitsy M0"},
          {"fqbn": "adafruit:samd:adafruit_itsybitsy_m4", "type": "ItsyBitsy M4"},
          {"fqbn": "MegaCoreX:megaavr:4809", "type": "Atmega4809"},
          {"fqbn": "esp32:esp32:esp32", "type": "ESP32 Dev module"}
        ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Cheackout repository
        uses: actions/checkout@v2

      # See: https://github.com/arduino/compile-sketches/README.md
      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: |
            # Use Board Manager to install the latest release of Arduino Boards for the toolchain
            - name: "arduino:avr"
            - name: "arduino:megaavr"
            # Install Adafruit SAMD
            - name: "adafruit:samd"
              source-url: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
            # Install MegaCoreX
            - name: "MegaCoreX:megaavr"
              source-url: https://mcudude.github.io/MegaCoreX/package_MCUdude_MegaCoreX_index.json
            # Install megaTinyCore via Boards Manager for the toolchain
            - name: "megaTinyCore:megaavr"
              source-url: http://drazzy.com/package_drazzy.com_index.json
            # Install ESP32
            - name: "esp32:esp32"
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          
